// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_WtbY43eaJWaFPIQSFlH1icRbESMSyRM',
    appId: '1:456425651664:web:your_web_app_id',
    messagingSenderId: '456425651664',
    projectId: 'challenge-and-risk',
    authDomain: 'challenge-and-risk.firebaseapp.com',
    storageBucket: 'challenge-and-risk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_WtbY43eaJWaFPIQSFlH1icRbESMSyRM',
    appId: '1:456425651664:android:e6ed77b71c5b4ba09c0dd5',
    messagingSenderId: '456425651664',
    projectId: 'challenge-and-risk',
    storageBucket: 'challenge-and-risk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_WtbY43eaJWaFPIQSFlH1icRbESMSyRM',
    appId: '1:456425651664:ios:your_ios_app_id',
    messagingSenderId: '456425651664',
    projectId: 'challenge-and-risk',
    storageBucket: 'challenge-and-risk.firebasestorage.app',
    iosBundleId: 'com.example.challengeAndRisk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_WtbY43eaJWaFPIQSFlH1icRbESMSyRM',
    appId: '1:456425651664:macos:your_macos_app_id',
    messagingSenderId: '456425651664',
    projectId: 'challenge-and-risk',
    storageBucket: 'challenge-and-risk.firebasestorage.app',
    iosBundleId: 'com.example.challengeAndRisk',
  );
}
